### PR TITLE
allow `/give machines` to give all unlocks

### PR DESCRIPTION
**Pull request by RWsYiffyMind**
hardcoding the path isn't the cleanest thing, but it's probably fine for a cheat (won't cause anything catastrophic if it ever breaks). Works locally, but I haven't tested in multiplayer (but LocalUse seems to be the way to trigger things that propagate to the network?)

### CODE REVIEW

**Comment by RWsYiffyMind** [comment]
forgot to tag #150

**Comment by RWsYiffyMind** [comment]
is it helpful for me to drop reminders on something that should be safe to merge, or is that just being a nag

**Comment by naelstrof** [comment]
Oh it is helpful actually. I get scatterbrained from all the stuff I take care of.

**Comment by naelstrof** [comment]
I made a small adjustment that has it unlock all the machines in the scene, regardless of the host's money.

It'll need to be adjusted again when cheats don't rely on a weird client->host ping pong.

https://github.com/naelstrof/KoboldKare/commit/8fe842d973dda36bddd69a3e506631eb9c5de41a#diff-b9cc6e8d9ea0f0d609d1f19f2b4b4b3b42852de6069813ae9b58fdfd1326c369R73

**Comment by omgitsraven** [comment]
Oh nice, thank you!  (I figured they could just use the money cheat too, heh...)

**Comment by RWsYiffyMind** [comment]
Oh nice, thank you! (I figured they could just use the money cheat too, heh...)

**Pull request merged**
