### PR TITLE
New shader for cum mozzarella streams

### PR DESCRIPTION
**Pull request by RWsYiffyMind**
Gives shading, wobbly edges and motion.  (Wrote most of it in a Custom Expression because I really prefer writing shaders in text...)   The normals are kind of faked but I think it looks good, especially for something mostly only visible in rapid motion anyway.
Gave the project its own Mozzarella prefab variant with the new material on it.   Also made it so that anything using mozzarella streams will pass their color to it.
Only downside is it does make the abrupt start of mozarella streams much more obvious, but I think that's a job for a separate pull request...

### CODE REVIEW

**Comment by RWsYiffyMind** [comment]
Oh yeah, I hadn't thought about that!  I just tried switching to OpenGL mode in editor, and it works there -- is it worth making a build too, or is that usually enough?

**Comment by RWsYiffyMind** [comment]
I've just resolved the merge conflicts that cropped up while this was waiting to be pulled.

Is there anything else I can do to confirm that this is ready to go?

**Comment by naelstrof** [comment]
Oh sorry! Was just really deep in a huge refactor. I'll be able to take a look soon.

**Comment by omgitsraven** [comment]
just bumping before a new conflict comes along!

**Comment by RWsYiffyMind** [comment]
just bumping before a new conflict comes along!
(sorry, I always forget which account I'm logged in with, LOL)

**Comment by naelstrof** [comment]
It looks really good, and is well implemented! Thank you! Sorry for the slow pull.

**Comment by RWsYiffyMind** [comment]
That's alright!  Thank you :)

**Comment by naelstrof** [comment]
I've added a mat cap and some emission to help it look correct in more light conditions, and it makes it painfully clear that the normals don't look quite right.

image

It's currently using cosines which end up creating this parabolic shape rather than a cylindrical one.
image

**Comment by naelstrof** [comment]
I'm going to see if I can't adjust it.

**Comment by naelstrof** [comment]
Wait, no cosine should make that cylinder normal, I'm not sure what's wrong.

**Comment by naelstrof** [comment]
image

Got it to look much better, I'm not actually sure if it's mathematically correct. I simply set the z component of the normal to 1 rather than 0.5. The normalization was extending the x and y portions of the normal in tangent space causing them to be a bit too extreme.

**Comment by naelstrof** [comment]
I ended up removing all the wobbliness, because there was no way to make it not artifact at the start and end of the LineRenderer. The built-in unity LineRenderer doesn't have enough fine-grain UV control to make it look consistent and normal.

I still like the rest of it though, here's the final look:
image

**Comment by naelstrof** [comment]
Setting Z to 1 wasn't the right solution either. I realize the circle shape comes from the relationship between sin and cos.

It was actually correct to set Z to to sin(acrossAng), and Y to cos(acrossAng) in tangent space.

**Comment by RWsYiffyMind** [comment]
Oh yeah sorry -- I very consciously just faked the normals because it was meant to be depicting something kind of fluid and chaotic anyway, and without the matcap it didn't have enough detail for getting it 'correct' to make an apparent enough difference to be worth the trouble of being precise.

The cos across y and and sin across z is the main idea behind turning the flat strip into a cylinder, yeah.  (I see you noticed that I'm only taking the top half of the wave, so it isn't a bell curve.)  Technically, if we wanted it to be TRULY convincing, we would have to actually _exaggerate_ that curve to compensate for the fact that the nearest part of the cylinder would be taking up more of the viewer's field of view due to foreshortening, but that distortion would have to be dependent on the fragment's distance from the camera -- which is absolutely technically doable, but like I said, for something that was _designed_ to be floppy and chaotic, it seemed like overkill, compared to just letting mild inaccuracies seem to originate from the natural distortions in the stream (if they were even recognizable at all under such rapid animation).

But the other part of the effect that I added was to have the stream becoming thinner and thicker regularly across its length, which initially I just did by varying its radius (and with it, the range that the y&z cos&sin interpolate over), but after watching the result for a while I realised that it would *also* have an effect on the x normal, allowing there to be highlights on the 'rising' edge of the blobs even on the part where it faces the viewer.   And at THAT point, I realised that those two effects would *both* have an impact on the z normal, and I was about to sit down and find the cross product to set it properly, but then I said "oh hell, it's a big chaotic splash anyway", and settled for normalizing against a constant z term, even though that would look wrong if it were something stationary enough for people to observe up close.  (I used a small z to exaggerate how apparent the effect of the other waves would be on the shading, just to make it more eye-catching; the exact amount of the z to normalize against is arbitrary because it would never be 'correct' whatever I set it to.

The one other flaw that I'm aware of, is the fact that I'm not compensating for the wildly changing length of the strip over time; I was getting ready to pass in a multiplier value indicating its current length in world coordinates, when I decided that I liked the sense of force implied by the much-more-rapid (in world space) oscillations at the start of each spurt anyway.

You can tell by now that one of my design principles was "just stop if it already looks good enough" -- maybe something I've picked up from being on the clock at my day job....   If this were a VR title, I'd have kept going until I'd gotten this all correct, because the inaccuracies would be dizzying to look at (speaking from experience), but for something played on a flat screen, and an element that would always be animating too rapidly to get a clear look at anyway, I figured 'aesthetically interesting' was close enough.  But I'll happily go back in and clean these things up properly if it's a concern.

The one thing I don't understand is what you meant by the "artifact at the start and end of the LineRenderer" that caused you to remove the wobbliness (which was my favourite part tbh!) -- are you referring to the base and the tip of the stream at any moment in time, or are you referring to the state of the strip as a whole at the beginning and end of its *animation*?

**Comment by naelstrof** [comment]
> The one thing I don't understand is what you meant by the "artifact at the start and end of the LineRenderer" that caused you to remove the wobbliness (which was my favourite part tbh!) -- are you referring to the base and the tip of the stream at any moment in time, or are you referring to the state of the strip as a whole at the beginning and end of its animation?

Yeah it was due to it being unaware of how long the strip was, so it made a sort of jagged ice-cream look at the start.
image
like that. It looked very strange, and instead of figuring out how to send the stream length to accommodate for it it was much easier to cut the feature.

You're welcome to make another pull request that doesn't cause that artifacting.

**Comment by RWsYiffyMind** [comment]
Hey, I feel silly, but here's something I just noticed that I think we both missed:  This pull request made changes to a file inside the project's installed copy of Mozzarella, in the packages folder.  Should I go and make that upstream in the Mozzarella repo instead?

**Comment by RWsYiffyMind** [comment]
Wait, actually, that repo doesn't seem to exist any more?  Does it just live inside KoboldKare now?

**Comment by naelstrof** [comment]
> Wait, actually, that repo doesn't seem to exist any more? Does it just live inside KoboldKare now?

Yeah, essentially. The old mozzarella package on git was a bloated systemic solution to a regular authored VFX problem.
I was considering switching even the line rendering to use regular Unity particle systems and hit callbacks. I haven't gotten around to sprucing things up yet, and I didn't want to fool people into thinking the old mozzarella package was maintained. So I just dumped it and replaced it with this.

**Pull request merged**
