### PR TITLE
Min/Max Breast size setting option

### PR DESCRIPTION
**Pull request by Draco18s**
This *should* work, but as Unity decided to take forever and a day to build asset bundles (and without doing that, the new addressable assets apparently get ignored) I'm not able to ensure it's actually working (in the UI options sense; gameplay wise I can be reasonably sure that works as desired).

Anyway, this provides a baseline to configure the maximal allowed range of body part values, for folks like myself, who don't want to see breasts on the 'bolds at all (but is more flexible than just an on-off switch). Could be applied to the other body parts as well. I'm not familiar enough with the UnityScriptableSettings package to handle things like ensuring that `min < max` within the UI itself.

### CODE REVIEW

**Comment by naelstrof** [comment]
Thank you so much for your contributions! I'm afraid this cannot be accepted because of two reasons. One I cannot explain, but the other I can say is that it goes against my imagined gameplay loop for the game.
(Specifically, selling kobolds you dislike, and breeding the kobolds you DO like.)

Otherwise, the code is perfectly clean, and the implementation is perfectly reasonable. I just cannot accept it due to the two aforementioned reasons. Sorry!

**Comment by Draco18s** [comment]
I certainly don't mind the aspect of "sell kobolds you don't like." No issues with that. It's just that as things stand right now, I *cannot have any kobolds that I do like.*

**Comment by naelstrof** [comment]
You're right. It's extremely difficult to breed that flat-chested kobolds, and I agree with you that it would fit my vision better if it was possible to simply sell kobolds with large breasts in order to minimize the genepool to a greater extent.

I promise that I want to include this pull request but I don't feel safe doing so, and I'm not allowed to explain why! I'm sorry.

**Comment by Draco18s** [comment]
I understand

**Pull request closed without merging**
