### PR TITLE
Allow further eggs without exiting and re-entering station

### PR DESCRIPTION
**Pull request by RWsYiffyMind**
Hello, it's me from #100 ; I wound up losing the nerve to post about cum and eggs on my professional account, hahah.

I poked around at the possibility of the changes I'd mentioned, but I decided to start with something smaller; commit message below:

A kobold laying in an OvipositionSpot will now lay eggs whenever they're able, without having to stand up and "use" the OvipositionSpot a second time to continue.

Made it only check every 3 seconds since there's no particular rush, just in case it would be detrimental to run this every single frame (I haven't read up much on what goes under the hood of these checks yet), but if that's needlessly cautious I could take out the lastEggCheckTime part and just check for an egg-ready kobold every frame...   (Though, having the check wait on the eggDelaySeconds when starting laying also prevents eggs from 'doubling up' if enough cum still left in the belly has time to produce a high enough egg value that quickly, though I'm not sure if it's possible for that to happen faster than the six-second delay anyway....)

Was tempted to have the `if (!KoboldReadyToLayEgg(k))` check inside of EggLayingRoutine, rather than have the "is a kobold in the station" check duplicated inside and outside of it, but it felt a little unintuitive to be repeatedly firing off a coroutine that almost always immediately breaks, rather than just checking before firing it off....   It might be worth it to cut down on duplicate code, though.   Let me know if it would be better to change it.

This does allow for the possibility of a (gradual) 'endless eggs' scenario, although, given that any animation spot in the game can make endless hearts, I'd imagine that that's not a major concern...

Probably worth mentioning, I have not had the opportunity to test this in multiplayer whatsoever; I can't see anything here that suggests that it would have unique problems there, but this being my first change, there could absolutely be context I'm missing.  I've tested it relatively thoroughly in single-player though and it doesn't seem to have introduced any problems.

### CODE REVIEW

**Comment by naelstrof** [comment]
Yeah this is only marginally troubling due to how often objects get spammed in KoboldKare. The egg laying stations were part of the solution to *prevent* huge piles of eggs.

I will merge this after I change how the pachinko and end-game kobold spawner works. The game is already suffering quite a bit from spam and I pay for every penny of that broadband lol:
image

**Comment by RWsYiffyMind** [comment]
Oh yikes!

Why are piles of hearts allowed, then?  I'm kicking around big heaps of them whenever I run around the farm because I leave kobolds in those animators just because it's nice to watch them, but I don't even want all the hearts, I've been dreading cleaning them all up....  Could the hearts be a factor in the bandwidth costs?  (Are there any kind of statistics on which objects are responsible for what percentage of bandwidth?)

**Comment by naelstrof** [comment]
Hahah yeah oh gosh, there shouldn't be piles of hearts either. Photon unfortunately doesn't have any profiling tools. I plan to create my own though-- In general I think 90% of my broadband issues is just from piles of hearts, piles of cosmetics, and piles of kobolds (From the late-game spawner).

Eggs are actually not an issue right now, I rarely see piles of eggs in multiplayer matches-- and I'm not sure if it's due to the egg laying stations-- or because eggs end up being really useful to consume (by planting, grinding, or selling).

**Comment by naelstrof** [comment]
I'll make it a priority to get some profiling tools running, then I'll gather some data to determine where we can have new props. For all I know all the broadband could be from the RPC calls I do for fluid transfers.

I'd much rather have piles of eggs, than piles of hearts/cosmetics.

**Comment by RWsYiffyMind** [comment]
yeah just for the record:
image

I was like "oh this must be normal, if this is what the game does by default", heh

I'm tempted to spitball suggestions for workarounds (have nearby hearts merge into larger ones once enough are present in a single area?) but yeah might as well wait until you've got some data to work with.

**Comment by naelstrof** [comment]
Yeah I really like the idea of two hearts touching each other and "pop" they are now one bigger heart. In fact fruit already change their scale based on their contents.

I'll see if I can prototype that as a solution for at least-- heart generation haha. I still need to fix the pachinko machine.

**Comment by RWsYiffyMind** [comment]
btw, I don't want to be a pest, but I don't want to let this go stale and get harder to merge if we're good to go now that the network stuff has been optimized?  was there anything else holding it back?

**Comment by naelstrof** [comment]
Oh shoot yeah, I'll merge it now. Thanks for the reminder.

**Pull request merged**
