### PR TITLE
UI Enhancement Files

### PR DESCRIPTION
**Pull request by FoxComment**
_Includes mod's C# (expecting it not to be used because... it's a poorly written mod that just replaced UI)

And all the New graphics for in game HUD with layout design refs   (Main thing)

### CODE REVIEW

**Comment by FoxComment** [comment]
Made it all wrong, sorry. Have to work on it a bit more.

**Comment by naelstrof** [comment]
Alright cool, checking it out now!

**Comment by FoxComment** [comment]
About non-functional things, yeaah, I wanted to add a UI dynamics thingy (slightly moves UI in the dicertion kobold moves) and 3D model in Equipment menu (But have and had no idea how to add this things without causing any issues). 
So all the code in there, in a first commit I made, but I decided to remove it right after because of my poor execution. But I'll be pleased to see such a functions, they just make visuals a lot nicer.

_And there's only one thing i gave up on fixing - Equipment layout. The right pane looks scuffed on any other screen aspect that is not 16:9._

**Comment by FoxComment** [comment]
I'd like to make edits into game's main, pause, save and options menus, but afraid of changing layouts/removing elements, cuz they might be refd to something somewhere. I also wanted to make some edits into stores' UI in game, but that's a bit more than a Simple re-design.

**Comment by FoxComment** [comment]
About icons... As I understood they're stored somewhere in a *database* var in *kobold*, but I'm too silly to figure out how it works. So I just replaced half of them. (Including key icons)

**Comment by naelstrof** [comment]
Feel free to be brave making changes. Are you okay with me making small edits and incorporating it into the main game? Or are you wanting it to work as a mod?

**Comment by naelstrof** [comment]
okay sweet, yeah it'll take me a bit of time, but I'll try to make commits to incorporate your changes in an acceptable manner. Since you're willing to incorporate it directly it's a lot easier haha.

**Pull request closed without merging**
